### ISSUE TITLE
Can not launch pyblish due to debug mode not being set

### ISSUE THREAD

**Issue by cb109** [pyblish/pyblish-win#7]
Hi,

I just installed pyblish **pyblish-1.1.0-x64-setup.exe** on WIndows 7 and could not launch the tool. It would open a shell and quit:

![err](https://cloud.githubusercontent.com/assets/6052590/9706422/b9e53d8a-54e4-11e5-9308-06c6ae3d437f.png)

I added a <code>debug = True</code> in https://github.com/pyblish/pyblish-qml/blob/master/pyblish_qml/app.py#L259 which made it open the application successfully.

Not sure whether I am missing a setupstep (environment variable maybe?) or if that just needs a different default value or fix.

Cheers

**Comment by mottosso** [comment]
Thanks @cb109 for the detailed summary. You're right, the Pyblish QML start menu item is a bit cryptic at the moment and not terribly useful. It has been superseded by [Pyblish Standalone](https://github.com/pyblish/pyblish-standalone) but not yet included in the Windows distribution.

For completeness, what happened when it told you it quit due to loneliness was this.
1. A Pyblish QML client awoke, awaiting input from a host, such as Maya or Max.
2. No host contacted the client within 5 seconds and thus the client chose to self-terminate.

Granted, not the most useful feature for a start-menu item. In order to play ball, you need to run it, and then quickly run a host to accompany it.

As an alternative, you can run this.

``` python
import pyblish_integration
pyblish_integration.setup()
pyblish_integration.show()
```

This will launch both a client and a server in the same console, meaning it will keep itself company and not self-terminate. This is what Standalone is doing.

I'll add standalone to the Windows build, it's been ready for a week or two now.

**Comment by mottosso** [comment]
I just updated Pyblish for Windows, you should now be seeing the Pyblish QML user interface when running Pyblish from the start-menu! Let me know if this solves the issue.

**Comment by cb109** [comment]
Hey @mottosso , thanks for the update. After reinstalling the pyblish standalone now launches fine!

A question on the side, how would my setup look so that I can do the <code>import pyblish_integration</code>? 
I don't see a **setup.py** anywhere, how would I install the package?

**Comment by mottosso** [comment]
Pyblish Integration, along with most other stable Pyblish projects, are all part of Pyblish for Windows.

Once installed, you should be able to run `import pyblish_integration` already, assuming you have the [`c:\Program Files\pyblish\pythonpath`](https://github.com/pyblish/pyblish-win/tree/master/pythonpath) directory on your PYTHONPATH. Pyblish for Windows is essentially an umbrella project for the latest stable versions of the Pyblish ecosystem.

You shouldn't have to think about this generally, installing this should suffice. But if you're interested in digging deeper or going bleeding edge, you can install repositories directly by cloning them and appending it's contents to your PYTHONPATH, so long as you also install its dependencies such as PyQt5 for Python 2.7.

I'm on Gitter if you're looking for more immediate feedback, I can take you through the steps if you'd like.
- https://gitter.im/pyblish/pyblish

**Comment by cb109** [comment]
I see :thumbsup: Thanks, and I'll post on Gitter when I have questions!

**Comment by mottosso** [comment]
Perfect, closing this for now, feel free to most new issues should you have any.
